### ISSUE TITLE
accumulo init

### ISSUE THREAD

**Issue by threadedblue** [apache/accumulo-docker#10]
Running a new image, 
$> docker run accumulo init .  Hangs, warns to be sure Zookeeper is running.
$> docker run accumulo sookeeper . Problem reading instance id out of hdfs at hdfs://localhost:8020/accumulo/instance_id

Do we have a catch 22?

**Comment by ctubbsii** [comment]
I don't have much experience running the Accumulo docker image, but `docker run accumulo sookeeper` (sic) does not look like any part of the instructions at https://github.com/apache/accumulo-docker/blob/master/README.md , even after replacing the `s` with `z` to correct the spelling of `zookeeper`.

Reading the instructions, it seems like ZooKeeper should already be running and available in the image prior to doing the `init`. Have you verified this is the case?

**Comment by threadedblue** [comment]
Guilty as charged on the typeo.

Thanks for the kick in the head.  I was misreading the command useage.  I have since tried running:

$> docker run zookeeper
and zk ran (after doing a few unexpected pulls).  After that,
$> docker run accumulo init
ran without a hitch.
