### ISSUE TITLE
Accumulo 2.0.0 is out...

### ISSUE THREAD

**Issue by larsw** [apache/accumulo-docker#11]
Hi,

Ref. the README; will you publish an official image soon?

**Comment by keith-turner** [comment]
I can update it for 2.0, but I Am not sure how to publish an image.

**Comment by ctubbsii** [comment]
@larsw Do you know what's involved in doing that?

**Comment by ctubbsii** [comment]
It seems like what might be required is for the Accumulo PMC to vote to release this Dockerfile as an official ASF release, and then anybody can issue a pull request to add an accumulo specification that points to the tagged ASF release at: https://github.com/docker-library/official-images

**Comment by volmasoft** [comment]
I'm not sure if progress on this has stalled, it seems like it may have for now?

If it was acceptable, I'd like to look at whether we can get 2 changes in before we release the first official version and we still potentially need to resolve the naming convention.

### Reduce the image size
This configuration suffers from the same issues as accumulo-proxy, see the issue discussion here: https://github.com/apache/accumulo-proxy/issues/22 
My intention is to allow the accumulo-proxy discussion to run it's course and then look at folding in the same code to accumulo-docker for consistency.

### Potential props change
Another discussion I kicked off is here: https://github.com/apache/accumulo-proxy/issues/21 
I personally think changing the approach to supplying properties would be a great thing but I don't want accumulo-proxy and accumulo-docker to be inconsistent.

### Tag naming/versioning convention
Looking at the e-mail thread it seems we haven't fully settled on a naming and versioning convention for the Docker image tags.

I'm happy to continue discussions across different issues/pulls, or happy to carve some time out and have a slack conversation if people would find that easier?

**Comment by ctubbsii** [comment]
> I'm not sure if progress on this has stalled, it seems like it may have for now?

Perhaps it has stalled a little, but as you pointed out, there is an e-mail thread on the topic. For proposed code changes, please feel free to submit pull requests or open issues. For discussions on release strategy and to "un-stall" the effort, please bring that to the mailing list.

> I'm happy to continue discussions across different issues/pulls, or happy to carve some time out and have a slack conversation if people would find that easier?

Slack conversations are great for informal, "brainstorming"-type conversations and for answering user questions, but any decisions regarding the direction of the project should be made on the developer mailing list. So, if you do have a conversation on Slack, please summarize the main points on the mailing list so anybody who did not participate there will have a chance to do so, and decisions can be made there.

Thanks for looking into this. The docker stuff definitely needs work and a champion or two to carry it forward, so your contributions in this area are appreciated.

**Comment by dlmarion** [comment]
The Dockerfile has been updated to release 2.1.0. Looking at the discussion here I don't think there is anything left to do here. Closing this ticket.
