### ISSUE TITLE
Instructions are a bit confusing

### ISSUE THREAD

**Issue by RangaSamudrala** [apache/accumulo-docker#25]
In the README.md file, I see the below text
```
Before you can run Accumulo services in Docker, you will need to install Accumulo, configure accumulo.properties, and initialize your instance with --upload-accumulo-props. This will upload configuration to Zookeeper and limit how much configuration needs to be set on the command line.

```bash
$ accumulo init --upload-accumulo-props
...

```

So, where is this supposed to be invoked? Are we to run this as **docker run** command or am I missing something here?

**Comment by dlmarion** [comment]
It looks like you will need to do this on the host, not in the Docker container. This will upload the properties to ZooKeeper and then the Accumulo services that are running in the Docker container will read them from ZooKeeper.

**Comment by RangaSamudrala** [comment]
It says "_you will need to install Accumulo_" . Please excuse me if I sound naive. May be I do not grasp the complexity that exists. But, isn't this defeating the purpose a bit? Wouldn't one want to just build an image and run it and not having to do all the preliminary stuff, including installing Accumulo to build and run Accumulo docker image?

**Comment by ctubbsii** [comment]
"install" here means "obtain the Accumulo binaries and set up the class path so you can run `accumulo init --upload-accumulo-props`". It doesn't mean you need to have it running locally... just that you need to have it installed to the point where you can execute that command.

@RangaSamudrala Your last comment appears to have been cut off after "For example,"

**Comment by RangaSamudrala** [comment]
Apologize I didn't complete the comment.  I come back here and see the response today. 

Removed the "for example..." text.

IMHO, we need to remove the statement "_you will need to install Accumulo_" in README. Accumulo binaries are installed as part of the the logic in Dockerfile. The user needs to modify `accumulo.properties` and run the build command. 

Also, as I have played with it for a while, do we really need to provide the option `--upload-accumulo-props`? It seems to work fine and _init_ process uploads properties to the zookeeper.

**Comment by ctubbsii** [comment]
I think that part of the instructions are explaining what is happening, not additional steps the user needs to take. As such, I don't think this looks confusing to me. However, please feel free to supply a pull request with wording changes you propose, if you think it can be improved. I'm going to close this ticket, though, because whether or not the instructions are confusing is very subjective, and we don't need this ticket open in order to consider any PR your might want to propose. A PR can be created at any time with proposed changes.

**Comment by sayyadshifa326-hue** [comment]
Before you can run Accumulo services in Docker, you will need to install Accumulo, configure accumulo.properties, and initialize your instance with --upload-accumulo-props. This will upload configuration to Zookeeper and limit how much configuration needs to be set on the command line.

```bash
$ accumulo init --upload-accumulo-props
...
