### ISSUE TITLE
Ports exposed by different components of Accumulo

### ISSUE THREAD

**Issue by RangaSamudrala** [apache/accumulo-docker#28]
Any reason why no documentation exists for ports that are used and exposed when running this image?

**Comment by EdColeman** [comment]
The standard ports are listed at https://accumulo.apache.org/docs/2.x/administration/in-depth-install. Is that not sufficient?  Actual ports used will depend on you configuration

**Comment by RangaSamudrala** [comment]
I guess, it would be helpful this documentation is linked or presented here.

**Comment by dlmarion** [comment]
@RangaSamudrala  - It's likely that this is something that we have not thought of because we are pretty familiar with the ports and configuration. If you feel like contributing this change so that others in the future don't run into the same issue, that would be welcomed.

**Comment by ctubbsii** [comment]
I think this issue can be closed, since the requested documentation already exists. Proposed changes are always welcome, but we don't need this ticket open to consider any PRs that somebody might offer.
